### PR TITLE
Use OS-independent methods for caching paths

### PR DESCRIPTION
**Pull request by alecglen**
Resolves https://github.com/cooperdff/nfl_data_py/issues/21.

### CODE REVIEW

**Comment by alecglen** [comment]
@cooperdff any concerns here? It would be a huge boost to my feedback loop if we could get this merged!

**Comment by cooperdff** [comment]
@alecglen thanks for the reminder! merged and will work on getting updated version pushed to pip

**Comment by alecglen** [comment]
@cooperdff reminder to get that released if it's not too much trouble! 🙇‍♂️

**Comment by cooperdff** [comment]
@alecglen new release is hot off the presses, please let me know if you run into any issues with it

**Pull request merged**
